name: actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actionlint.yaml"
  push:
    branches: [main, master]
    paths:
      - ".github/workflows/**"
      - ".github/actionlint.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Run actionlint
        uses: raven-actions/actionlint@205b530c5d9fa8f44ae9ed59f341a0db994aa6f8 # v2.1.2
        with:
          fail-on-error: true
